retail:
  outputs:
    dev:
      dbname: airflow
      host: postgres
      pass: airflow
      port: 5432
      schema: public
      threads: 2
      type: postgres
      user: airflow
  target: dev